version: "2"
services:
  client:
    image: "node:14-alpine"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/home/node/app
      - ../pi-hosted/images:/home/node/app/public/assets/tools
    ports:
      - 5000:5000
    command: "npm run dev"
