version: "3"
services:
  client:
    image: "node:14-alpine"
    working_dir: /app
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: "npm run dev"
