version: "2"
services:
  # client:
  #   image: "node:14-alpine"
  #   user: "node"
  #   working_dir: /home/node/app/client
  #   environment:
  #     - NODE_ENV=dev
  #   volumes:
  #     - ./client:/home/node/app/client
  #   ports:
  #     - 5000:5000
  #   command: "npm run dev"

  server:
    image: "node:14-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
      - PORT=5150
    volumes:
      - ./:/home/node/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5150:5150
    command: "npm run docker"